BrewDay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

core/urls.py
from django.conf.urls import url, include
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='register.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('brew/', views.BrewView.as_view(), name='brew'),
    path('recipe/', views.RecipeView.as_view(), name='recipe'),
    path('recipe/management', views.RecipeManagement.as_view(), name='recipe-management'),
    path('profile/', views.IngredientView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('recommendation/', views.RecommendationView.as_view(), name='recommendation'),
    path('', views.HomeView.as_view(), name='home'),
]

templates/home.html
{% extends 'layout-brew.html' %}
{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="owl-carousel owl-loaded owl-nav-dots-inner" data-options='{"items":1,"loop":true}'>
    <div class="owl-item">
        <div class="slider-item" style="background-color:#3D3D3D; background-image: url('{% static 'img/bg-1.jpg' %}')">
            <div class="container">
                <div class="slider-item-inner">
                    <div class="slider-item-caption-left slider-item-caption-white">
                        <h4 class="slider-item-caption-title">Are you ready for some brewing experience?</h4>
                        <p class="slider-item-caption-desc">If yes, Piva is a great place for you.</p>
                        <a class="btn btn-lg btn-ghost btn-white popup-text" href="#nav-login-dialog">SAY NO MORE!</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="owl-item">
        <div class="slider-item" style="background-color:#3D3D3D; background-image: url('{% static 'img/bg-2.png' %}')">
            <div class="container">
                <div class="slider-item-inner">
                    <div class="slider-item-caption-left slider-item-caption-white">
                        <h4 class="slider-item-caption-title">Enter your ingredients and start brewing!</h4>
                        <a class="btn btn-lg btn-ghost btn-white popup-text" href="#nav-account-dialog" data-effect="mfp-move-from-top">Register</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/layout-brew.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>

<head>
    <title>Piva {% block title %}{% endblock %}</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='http://fonts.googleapis.com/css?family=Roboto:500,300,700,400italic,400' rel='stylesheet' type='text/css'>
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'> -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'> -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyles.css' %}">

</head>

<body>
    <div class="global-wrapper clearfix" id="global-wrapper">
        <div class="navbar-before mobile-hidden">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p class="navbar-before-sign">Piva</p>

                    </div>
                    <div class="col-md-6">
                        <ul class="nav navbar-nav navbar-right navbar-right-no-mar">
                            <li><a href="#">About</a>
                            </li>
                            <li><a href="#">Contact</a>
                            </li>
                            <li><a href="#">Help</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="mfp-with-anim mfp-hide mfp-dialog clearfix" id="nav-login-dialog">
            <h3 class="widget-title">Login</h3>
            <p>Welcome, please login.</p>
            <hr />

            <form method="post" action="{% url 'core:login' %}">{% csrf_token %}
                <div class="form-group">
                    <label>Username</label>
                    <input class="form-control" name="username" type="text" required/>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" name="password" type="password" required/>

                </div>

                <input class="btn btn-primary" name="pop-up-login-button" type="submit" value="Login" />
            </form>

            <div class="gap gap-small"></div>
            <ul class="list-inline">
                <li><a href="#nav-account-dialog" class="popup-text">Not a member?</a>
                </li>
                <li><a href="#nav-pwd-dialog" class="popup-text">Forgot my password.</a>
                </li>
            </ul>
        </div>
        <div class="mfp-with-anim mfp-hide mfp-dialog clearfix" id="nav-account-dialog">
            <h3 class="widget-title">Create Piva Account!</h3>
            <p>Brew Brew Brew!</p>
            <hr />

            <form method="post" action="{% url 'core:register' %}">{% csrf_token %}
                <div class="form-group">
                    <label>Username</label>
                    <input class="form-control" name="username" type="text" required/>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" name="email" type="text" required/>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" name="password" type="password" required/>
                </div>
                <div class="form-group">
                    <label>Password Again</label>
                    <input class="form-control" name="password2" type="password" required/>

                </div>

                <div class="checkbox">
                    <p>
                        <p>I have read and understand the user contract.</p>
                </div>
                <input class="btn btn-primary" type="submit" name="sign-up" value="Sign up" />
            </form>

            <div class="gap gap-small"></div>
            <ul class="list-inline">
                <li><a href="#nav-login-dialog" class="popup-text">Already have an account?</a>
                </li>
            </ul>
        </div>
        <div class="mfp-with-anim mfp-hide mfp-dialog clearfix" id="nav-pwd-dialog">
            <h3 class="widget-title">Reset Password</h3>
            <p>Enter your e-mail.</p>
            <hr />
            <form>
                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" type="text" />
                </div>
                <input class="btn btn-primary" type="submit" value="Reset Password" />
            </form>
        </div>
        <nav class="navbar navbar-inverse navbar-main yamm">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-nav-collapse" area_expanded="false"><span class="sr-only">Main Menu</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'core:home' %}">
                        <p>Piva</p>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="main-nav-collapse">
                    {% if request.user.is_authenticated %}
                        <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="{% url 'core:profile' %}" name="navbar-name" data-effect="mfp-move-from-top" class="">{{ request.user.username }}</a>
                        </li>
                    </ul>
                    {% endif %}
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="{% url 'core:recipe' %}"> Recipes<i class="drop-caret" data-toggle="dropdown"></i></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="{% url 'core:brew' %}"> Brew!<i class="drop-caret" data-toggle="dropdown"></i></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="{% url 'core:recommendation' %}"> Recommendation Tool<i class="drop-caret" data-toggle="dropdown"></i></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'core:logout' %}" name="navbar-logout" class="glyphicon glyphicon-log-out"></a>
                        </li>
                        {% else %}
                        <li><a href="#nav-login-dialog" data-effect="mfp-move-from-top" name="pop-up-login" class="popup-text">Login</a>
                        </li>
                        <li><a href="#nav-account-dialog" data-effect="mfp-move-from-top" name="pop-up-signup" class="popup-text">Sign up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}


        <footer class="main-footer">
            <div class="container">
                <div class="row row-col-gap">
                    <div class="col-md-2">
                        <img style="margin-bottom: 2em" src="{% static 'img/logo.png' %}" alt="Image Alternative text" title="Image Title" height="130" width="115"/>
                    </div>
                    <div class="col-md-3">
                        <h4 style="margin-top: 1em">Piva!</h4>
                        <p>It is a web-based application for brewers all around the world.
                            If you have any questions, please don't hesitate to contact us.</p>
                    </div>
                    <div class="col-md-3">
                        <div class="gap-small"></div>
                        <p style="font-size: 10px">We are not responsible for the actions of the users. If you encounter any problems or any copyright issue, please contact us. </p>
                    </div>
                </div>
                <ul class="main-footer-links-list">
                    <li><a href="#">About Us</a>
                    </li>
                    <li><a href="#">Legal</a>
                    </li>
                    <li><a href="#">Support & Customer Service</a>
                    </li>
                    <li><a href="#">Blog is coming soon!</a>
                    </li>
                    <li><a href="#">Privacy</a>
                    </li>
                </ul>


            </div>
        </footer>
       </div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/icheck.js' %}"></script>
    <script src="{% static 'js/ionrangeslider.js' %}"></script>
    <script src="{% static 'js/jqzoom.js' %}"></script>
    <script src="{% static 'js/card-payment.js' %}"></script>
    <script src="{% static 'js/owl-carousel.js' %}"></script>
    <script src="{% static 'js/magnific.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    {% block style %}{% endblock %}

</body>
</html>

templates/recipes.html
{% extends 'layout-brew.html' %}
{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
<style>
.panel-table .panel-body{
  padding:0;
}

.panel-table .panel-body .table-bordered{
  border-style: none;
  margin:0;
}

.panel-table .panel-body .table-bordered > thead > tr > th:first-of-type {
    text-align:center;
    width: 100px;
}

.panel-table .panel-body .table-bordered > thead > tr > th:last-of-type,
.panel-table .panel-body .table-bordered > tbody > tr > td:last-of-type {
  border-right: 0px;
}

.panel-table .panel-body .table-bordered > thead > tr > th:first-of-type,
.panel-table .panel-body .table-bordered > tbody > tr > td:first-of-type {
  border-left: 0px;
}

.panel-table .panel-body .table-bordered > tbody > tr:first-of-type > td{
  border-bottom: 0px;
}

.panel-table .panel-body .table-bordered > thead > tr:first-of-type > th{
  border-top: 0px;
}

.panel-table .panel-footer .pagination{
  margin:0;
}

/*
used to vertically center elements, may need modification if you're not using default sizes.
*/
.panel-table .panel-footer .col{
 line-height: 34px;
 height: 34px;
}

.panel-table .panel-heading .col h3{
 line-height: 30px;
 height: 30px;
}

.panel-table .panel-body .table-bordered > tbody > tr > td{
  line-height: 34px;
}
</style>
<div class="gap-small"></div>
<div class="row" data-gutter="15">
    <div class="col-md-4 col-md-offset-1">
        <div class="product">
            <ul class="product-labels">
                <li>Add Recipe</li>
            </ul>
            <div class="box-lg">
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <table class="table table-striped table-bordered table-list">
                            <thead>
                                <tr>
                                    <td><input name="recipeName" type="text" placeholder="Recipe Name" required></td>
                                    <td><button class="btn btn-success pull-right" name="submit"><em class="fa fa-beer"> Create Recipe</em></button></td>
                                </tr>
                            </thead>
                        </table>
                        <div class="gap-small"></div>
                        <table class="table table-striped table-bordered table-list">
                            <thead>
                                <tr>
                                    <th>Ingredient</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Malt</td>
                                    <td><input name="Malt" type="text" placeholder="0.0" ></td>
                                </tr>
                                <tr>
                                    <td>Hops</td>
                                    <td><input name="Hops" type="text" placeholder="0.0" ></td>
                                </tr>
                                <tr>
                                    <td>Yeast</td>
                                    <td><input name="Yeast" type="text" placeholder="0.0" ></td>
                                </tr>
                                <tr>
                                    <td>Sugar</td>
                                    <td><input name="Sugar" type="text" placeholder="0.0" ></td>
                                </tr>
                                <tr>
                                    <td>Additive</td>
                                    <td><input name="Additive" type="text" placeholder="0.0" ></td>
                                </tr>
                                <tr>
                                    <td><input name="new-ingredient-name" type="text" placeholder="Enter the name..."></td>
                                    <td><input name="new-ingredient-amount" type="text" placeholder="Enter the amount..."></td>
                                </tr>
                            </tbody>
                        </table>

                        <div class="gap-small"></div>
                    </form>
                </div>
            </div>



        </div>
    </div>
    <div class="col-md-1"></div>

    {% for recipe in recipes %}
        <form action="{% url 'core:recipe-management' %}" method="post">{% csrf_token %}
            <div class="col-md-4 col-md-offset-1">
                <div class="product">
                    <ul class="product-labels">
                        <li>{{ recipe.name }}</li>
                    </ul>
                    <div class="box-lg" >
                        <div class="gap-small"></div>
                        <div class="gap-small"></div>
                        <div class="row">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col col-xs-4">
                                        <h3 class="panel-title">Ingredients</h3>
                                    </div>
                                    <div class="col col-xs-8">
                                        <button class="btn btn-danger pull-right" name="delete"><em class="fa fa-trash"> Delete</em></button>
                                        <button class="btn btn-success pull-right" name="brew" style="margin-right: 10px;"><em class="fa fa-beer"> Brew!</em></button>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <table class="table table-striped table-bordered table-list">
                                    <thead>
                                        <tr>
                                            <th>Ingredient</th>
                                            <th>Amount</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in recipe.ingredient_set.all %}
                                            <tr>
                                                <td>{{ item.name }}</td>
                                                <td><input name="{{ item.name }}" type="text" placeholder="{{ item.amount }}"></td>
                                            </tr>
                                        {% endfor %}
                                        <tr>
                                            <td><input name="new-ingredient-name" type="text" placeholder="Enter the name..."></td>
                                            <td><input name="new-ingredient-amount" type="text" placeholder="Enter the amount..."></td>
                                        </tr>

                                    </tbody>
                                </table>

                                <div class="gap-small"></div>
                                <button class="btn btn-info pull-right" name="update"><em class="fa fa-pencil"> Update</em></button>
                                <input name="recipe-id" value="{{ recipe.id }}" hidden>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1"></div>
        </form>
    {% endfor %}
</div>
{% endblock %}

templates/recommendation.html
{% extends 'layout-brew.html' %}
{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
<style>
.panel-table .panel-body{
  padding:0;
}

.panel-table .panel-body .table-bordered{
  border-style: none;
  margin:0;
}

.panel-table .panel-body .table-bordered > thead > tr > th:first-of-type {
    text-align:center;
    width: 100px;
}

.panel-table .panel-body .table-bordered > thead > tr > th:last-of-type,
.panel-table .panel-body .table-bordered > tbody > tr > td:last-of-type {
  border-right: 0px;
}

.panel-table .panel-body .table-bordered > thead > tr > th:first-of-type,
.panel-table .panel-body .table-bordered > tbody > tr > td:first-of-type {
  border-left: 0px;
}

.panel-table .panel-body .table-bordered > tbody > tr:first-of-type > td{
  border-bottom: 0px;
}

.panel-table .panel-body .table-bordered > thead > tr:first-of-type > th{
  border-top: 0px;
}

.panel-table .panel-footer .pagination{
  margin:0;
}

/*
used to vertically center elements, may need modification if you're not using default sizes.
*/
.panel-table .panel-footer .col{
 line-height: 34px;
 height: 34px;
}

.panel-table .panel-heading .col h3{
 line-height: 30px;
 height: 30px;
}

.panel-table .panel-body .table-bordered > tbody > tr > td{
  line-height: 34px;
}
</style>
<div class="gap-small"></div>


    <div class="row" data-gutter="15">
        <div class="col-md-3 col-md-offset-1">
            <div class="product">
                <div class="row">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col col-xs-6">
                                <h3 class="panel-title">My Ingredients</h3>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-bordered table-list">
                            <thead>
                                <tr>
                                    <th>Ingredient</th>
                                    <th>Mount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ingredient in ingredients %}
                                <tr>
                                    <td>{{ ingredient.name }}</td>
                                    <td>{{ ingredient.amount }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>


        <div class="col-md-4 col-md-offset-1">
            <div class="product">
                <div class="gap-small"></div>
                <div align="center">
                    <form action="" method="post">{% csrf_token %}
                    <button class="btn-lg btn-success" name="submit"><i class="fa fa-cog" ></i> Recommend!</button>
                    </form>
                </div>
                <div class="gap-small"></div>
            </div>
        </div>

{#        <div class="row">#}
            <div class="col-md-4 col-md-offset-1">
            {% for recipe in recipes %}
            <div class="product">
                <ul class="product-labels">
                    <li>{{ recipe.name }}</li>
                </ul>

                <div class="box-lg" >
                    <div class="gap-small"></div>

                    <div class="gap-small"></div>

                    <div class="row">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col col-sm-10 col-sm-offset-2">
                                    <form action="{% url 'core:recipe-management' %}" method="post">{% csrf_token %}
                                        <button class="btn btn-success" name="brew" style="margin-right: 10px; width: 80%; height: 50px"><em class="fa fa-beer"> Brew!</em></button>
                                        <input type="hidden" name="recipe-id" value="{{ recipe.id }}">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="panel-body">
                            <table class="table table-striped table-bordered table-list">
                                <thead>
                                    <tr>
                                        <th>Ingredient</th>
                                        <th>Mount</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for ingredient in recipe.ingredient_set.all %}
                                <tr>
                                    <td>{{ ingredient.name }}</td>
                                    <td>{{ ingredient.amount }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <div class="gap-small"></div>
            {% endfor %}
        </div>
    </div>

{#    </div>#}

{% endblock %}

templates/register.html
{% extends 'layout-brew.html' %}
{% block title %}Register{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <header class="page-header">
                <h1 class="page-title" style="text-align: center;">Login or Register</h1>
            </header>
            <div class="box-lg">
                <div class="row" data-gutter="60">
                    <div class="col-md-6">
                        <h3 class="widget-title">Login</h3>

                        <form method="post" action="{% url 'core:login' %}">{% csrf_token %}
                            <div class="form-group">
                                <label>Username</label>
                                <input class="form-control" name="username" type="text" required/>
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input class="form-control" name="password" type="password" required/>
                            </div>

                            <input class="btn btn-primary" type="submit" value="Login" />
                        </form>
                        <br /><a href="#">Forgot password?</a>
                    </div>

                    <div class="col-md-6">
                        <h3 class="widget-title">Register</h3>

                        <form method="post" action="{% url 'core:register' %}">{% csrf_token %}
                            <div class="form-group">
                                <label>Username</label>
                                <input class="form-control" name="username" type="text" required/>
                            </div>
                            <div class="form-group">
                                <label>E-mail</label>
                                <input class="form-control" name="email" type="text" required/>
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input class="form-control" name="password" type="password" required/>
                            </div>
                            <div class="form-group">
                                <label>Password again</label>
                                <input class="form-control" name="password2" type="password" required/>

                            </div>
                            <input class="btn btn-primary" type="submit" value="Create account" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}